### ISSUE TITLE
demo崩溃

### ISSUE THREAD

**Issue by JIAZoro** [BAHome/BAAlert#1]
模拟器8.1下运行demo，点击类似系统alert弹出的框，点击下方的取消，确定按钮，都会crash
定位到BAAlert.m第498行：BAKit_WeakSelf。
Thread 1：EXC_BAD_ACCESS(code=EXC_I386_GPFLT)

**Comment by boai** [comment]
我刚试了 8.1 的模拟器，没有崩溃！有问题加我QQ：137361770

**Comment by boai** [comment]
此问题已修复，详见： 1.1.5.1、删除原有封装内部按钮点击事件中 ba_dismissAlertView 方法，此方法可在外部自由调用  <br>
